import type { HullDef } from '../core/types';

/**
 * Layout tokens: r reactor, e engine, j jump, l life support, n sensors (core slots, size = coreSize);
 * S/M/L free slots; '.' empty cell. Orthogonal neighbours matter for adjacency modules.
 */
export const HULLS: HullDef[] = [
  {
    id: 'wayfarer',
    layout: ['rSe', 'jMl', 'nML'],
    mass: 50,
    cargoCells: 10,
    cargoCols: 5,
    fuel: 60,
    supplies: 60,
    hp: 100,
    price: 9000,
    crew: 2,
    coreSize: 'S',
    agility: 1,
    tier: 1,
  },
  {
    id: 'kestrel',
    layout: ['rSe', 'jSl', 'nM.'],
    mass: 30,
    cargoCells: 4,
    cargoCols: 2,
    fuel: 55,
    supplies: 70,
    hp: 60,
    price: 12500,
    crew: 1,
    coreSize: 'S',
    agility: 1.35,
    tier: 2,
  },
  {
    id: 'mule',
    layout: ['rSe', 'jMl', 'nMS'],
    mass: 45,
    cargoCells: 16,
    cargoCols: 4,
    fuel: 50,
    supplies: 70,
    hp: 90,
    price: 14500,
    crew: 2,
    coreSize: 'S',
    agility: 0.8,
    tier: 2,
  },
  {
    id: 'swift',
    layout: ['re', 'jl', 'nS', 'SM'],
    mass: 22,
    cargoCells: 3,
    cargoCols: 3,
    fuel: 40,
    supplies: 40,
    hp: 45,
    price: 15500,
    crew: 1,
    coreSize: 'S',
    agility: 1.7,
    tier: 2,
  },
  {
    id: 'borer',
    layout: ['rMe', 'jSl', 'nLM', 'SSS'],
    mass: 85,
    cargoCells: 18,
    cargoCols: 6,
    fuel: 90,
    supplies: 90,
    hp: 150,
    price: 31000,
    crew: 3,
    coreSize: 'M',
    agility: 0.7,
    tier: 3,
  },
  {
    id: 'behemoth',
    layout: ['rMMe', 'jLLl', 'nMMS', '.SS.'],
    mass: 130,
    cargoCells: 36,
    cargoCols: 6,
    fuel: 140,
    supplies: 120,
    hp: 220,
    price: 52000,
    crew: 4,
    coreSize: 'M',
    agility: 0.55,
    tier: 3,
  },
];

export const HULLS_BY_ID: Record<string, HullDef> = Object.fromEntries(HULLS.map((h) => [h.id, h]));

/** Non-player hulls (creatures, turrets). Never sold in shipyards; they only provide room layouts for enemies. */
export const NPC_HULLS: HullDef[] = [
  {
    id: 'swarmer',
    layout: ['rSe', 'jln'],
    mass: 14,
    cargoCells: 0,
    cargoCols: 1,
    fuel: 20,
    supplies: 20,
    hp: 40,
    price: 3000,
    crew: 0,
    coreSize: 'S',
    agility: 1.7,
    tier: 0,
  },
  {
    id: 'maw',
    layout: ['rMe', 'jSl', 'nMS'],
    mass: 90,
    cargoCells: 0,
    cargoCols: 1,
    fuel: 40,
    supplies: 40,
    hp: 150,
    price: 20000,
    crew: 0,
    coreSize: 'S',
    agility: 0.7,
    tier: 0,
  },
  {
    id: 'turret',
    layout: ['rSe', 'jln', 'SS.'],
    mass: 60,
    cargoCells: 0,
    cargoCols: 1,
    fuel: 10,
    supplies: 10,
    hp: 90,
    price: 8000,
    crew: 0,
    coreSize: 'S',
    agility: 0,
    tier: 0,
  },
];
for (const h of NPC_HULLS) HULLS_BY_ID[h.id] = h;
