import type { HullDef } from '../core/types';

/**
 * Layout tokens: r reactor, e engine, j jump, l life support, n sensors (core slots, size = coreSize);
 * S/M/L free slots; '.' empty cell. Orthogonal neighbours matter for adjacency modules.
 */
export const HULLS: HullDef[] = [
  {
    id: 'wayfarer',
    role: 'universal',
    layout: ['rSe', 'jMl', 'nML'],
    mass: 50,
    cargoCells: 10,
    cargoCols: 5,
    fuel: 60,
    supplies: 60,
    hp: 100,
    price: 9000,
    crew: 2,
    coreSize: 'S',
    agility: 1,
    tier: 1,
  },
  {
    id: 'kestrel',
    role: 'scout',
    layout: ['rSe', 'jSl', 'nM.'],
    mass: 30,
    cargoCells: 4,
    cargoCols: 2,
    fuel: 55,
    supplies: 70,
    hp: 60,
    price: 12500,
    crew: 1,
    coreSize: 'S',
    agility: 1.35,
    tier: 2,
  },
  {
    id: 'mule',
    role: 'cargo',
    layout: ['rSe', 'jMl', 'nMS'],
    mass: 45,
    cargoCells: 16,
    cargoCols: 4,
    fuel: 50,
    supplies: 70,
    hp: 90,
    price: 14500,
    crew: 2,
    coreSize: 'S',
    agility: 0.8,
    tier: 2,
  },
  {
    id: 'swift',
    role: 'courier',
    layout: ['re', 'jl', 'nS', 'SM'],
    mass: 22,
    cargoCells: 3,
    cargoCols: 3,
    fuel: 40,
    supplies: 40,
    hp: 45,
    price: 15500,
    crew: 1,
    coreSize: 'S',
    agility: 1.7,
    tier: 2,
  },
  {
    id: 'borer',
    role: 'mining',
    layout: ['rMe', 'jSl', 'nLM', 'SSS'],
    mass: 85,
    cargoCells: 18,
    cargoCols: 6,
    fuel: 90,
    supplies: 90,
    hp: 150,
    price: 46000,
    crew: 3,
    coreSize: 'M',
    agility: 0.7,
    tier: 3,
  },
  {
    id: 'behemoth',
    role: 'heavy',
    layout: ['rMMe', 'jLLl', 'nMMS', '.SS.'],
    mass: 130,
    cargoCells: 36,
    cargoCols: 6,
    fuel: 140,
    supplies: 120,
    hp: 220,
    price: 74000,
    crew: 4,
    coreSize: 'M',
    agility: 0.55,
    tier: 3,
  },
  {
    id: 'shuttle',
    role: 'budget',
    layout: ['rSe', 'jln'],
    mass: 25,
    cargoCells: 3,
    cargoCols: 3,
    fuel: 35,
    supplies: 40,
    hp: 40,
    price: 4200,
    crew: 1,
    coreSize: 'S',
    agility: 1,
    tier: 1,
  },
  {
    id: 'courier',
    role: 'courier',
    layout: ['re', 'jl', 'nS'],
    mass: 24,
    cargoCells: 4,
    cargoCols: 2,
    fuel: 50,
    supplies: 40,
    hp: 45,
    price: 7000,
    crew: 1,
    coreSize: 'S',
    agility: 1.3,
    tier: 1,
  },
  {
    id: 'scout',
    role: 'explorer',
    layout: ['rSe', 'jSl', 'nSS'],
    mass: 38,
    cargoCells: 4,
    cargoCols: 2,
    fuel: 85,
    supplies: 60,
    hp: 70,
    price: 11500,
    crew: 2,
    coreSize: 'S',
    agility: 1.15,
    tier: 1,
  },
  {
    id: 'prospector',
    role: 'mining',
    layout: ['rMe', 'jSl', 'nMM'],
    mass: 60,
    cargoCells: 8,
    cargoCols: 4,
    fuel: 70,
    supplies: 70,
    hp: 110,
    price: 15000,
    crew: 2,
    coreSize: 'S',
    agility: 0.9,
    tier: 2,
  },
  {
    id: 'merchant',
    role: 'trader',
    layout: ['rSe', 'jMl', 'nMM', 'MS.'],
    mass: 70,
    cargoCells: 24,
    cargoCols: 6,
    fuel: 60,
    supplies: 70,
    hp: 100,
    price: 31000,
    crew: 2,
    coreSize: 'S',
    agility: 0.95,
    tier: 2,
  },
  {
    id: 'armored',
    role: 'armored',
    layout: ['rMe', 'jMl', 'nMM', 'LS.'],
    mass: 110,
    cargoCells: 26,
    cargoCols: 6,
    fuel: 80,
    supplies: 90,
    hp: 260,
    price: 58000,
    crew: 3,
    coreSize: 'M',
    agility: 0.5,
    tier: 3,
  },
  {
    id: 'yacht',
    role: 'passenger',
    layout: ['rMe', 'jLl', 'nLM', 'MM.'],
    mass: 75,
    cargoCells: 6,
    cargoCols: 3,
    fuel: 110,
    supplies: 140,
    hp: 120,
    price: 92000,
    crew: 5,
    coreSize: 'M',
    agility: 1.1,
    tier: 3,
  },
  {
    id: 'expedition',
    role: 'expedition',
    layout: ['rMMe', 'jMMl', 'nMLS'],
    mass: 115,
    cargoCells: 20,
    cargoCols: 5,
    fuel: 230,
    supplies: 160,
    hp: 170,
    price: 110000,
    crew: 4,
    coreSize: 'M',
    agility: 0.75,
    tier: 3,
  },
];

export const HULLS_BY_ID: Record<string, HullDef> = Object.fromEntries(HULLS.map((h) => [h.id, h]));

/** Non-player hulls (creatures, turrets). Never sold in shipyards; they only provide room layouts for enemies. */
export const NPC_HULLS: HullDef[] = [
  {
    id: 'swarmer',
    role: 'npc',
    layout: ['rSe', 'jln'],
    mass: 14,
    cargoCells: 0,
    cargoCols: 1,
    fuel: 20,
    supplies: 20,
    hp: 40,
    price: 3000,
    crew: 0,
    coreSize: 'S',
    agility: 1.7,
    tier: 0,
  },
  {
    id: 'maw',
    role: 'npc',
    layout: ['rMe', 'jSl', 'nMS'],
    mass: 90,
    cargoCells: 0,
    cargoCols: 1,
    fuel: 40,
    supplies: 40,
    hp: 150,
    price: 20000,
    crew: 0,
    coreSize: 'S',
    agility: 0.7,
    tier: 0,
  },
  {
    id: 'turret',
    role: 'npc',
    layout: ['rSe', 'jln', 'SS.'],
    mass: 60,
    cargoCells: 0,
    cargoCols: 1,
    fuel: 10,
    supplies: 10,
    hp: 90,
    price: 8000,
    crew: 0,
    coreSize: 'S',
    agility: 0,
    tier: 0,
  },
];
for (const h of NPC_HULLS) HULLS_BY_ID[h.id] = h;
