import type { StationTypeDef, StationTypeId } from '../core/types';

const w = (core: number, inner: number, outer: number, rim: number) => ({ core, inner, outer, rim });

export const STATION_TYPES: StationTypeDef[] = [
  {
    id: 'mining',
    produces: {
      iron_ore: 0.9,
      silicates: 0.8,
      rare_ore: 0.6,
      water_ice: 0.7,
      crystals: 0.4,
      radioactives: 0.4,
    },
    consumes: {
      machinery: 0.8,
      protein: 0.7,
      grain: 0.5,
      spare_parts: 0.8,
      fusion_cells: 0.5,
      medicine: 0.4,
    },
    shipyard: 1,
    cartography: false,
    intel: false,
    blackMarket: false,
    contractBias: { supply: 3, freight: 2, rescue: 1, passenger: 1 },
    weight: w(2, 4, 4, 3),
    lawful: true,
  },
  {
    id: 'agricultural',
    produces: { grain: 0.9, protein: 0.7, fresh_produce: 0.8, spirits: 0.5, textiles: 0.3 },
    consumes: {
      machinery: 0.6,
      polymers: 0.6,
      medicine: 0.6,
      electronics: 0.4,
      water_ice: 0.6,
      fusion_cells: 0.3,
    },
    shipyard: 0,
    cartography: false,
    intel: false,
    blackMarket: false,
    contractBias: { freight: 3, passenger: 2, supply: 2 },
    weight: w(1, 4, 4, 3),
    lawful: true,
  },
  {
    id: 'industrial',
    produces: {
      metals: 0.9,
      alloys: 0.7,
      polymers: 0.8,
      construction: 0.7,
      machinery: 0.8,
      spare_parts: 0.8,
      fusion_cells: 0.4,
    },
    consumes: {
      iron_ore: 0.9,
      silicates: 0.7,
      hydrocarbons: 0.8,
      rare_ore: 0.6,
      protein: 0.5,
      grain: 0.4,
      water_ice: 0.4,
      radioactives: 0.4,
    },
    shipyard: 3,
    cartography: false,
    intel: false,
    blackMarket: false,
    contractBias: { freight: 3, supply: 3, courier: 1 },
    weight: w(5, 4, 2, 1),
    lawful: true,
  },
  {
    id: 'scientific',
    produces: {
      electronics: 0.7,
      optics: 0.7,
      computers: 0.6,
      medicine: 0.6,
      vaccines: 0.6,
      biosamples: 0.5,
    },
    consumes: {
      crystals: 0.7,
      rare_metals: 0.6,
      polymers: 0.5,
      hydrocarbons: 0.4,
      fresh_produce: 0.6,
      spirits: 0.4,
      art: 0.3,
    },
    shipyard: 2,
    cartography: true,
    intel: false,
    blackMarket: false,
    contractBias: { survey: 3, courier: 3, passenger: 2, rescue: 1 },
    weight: w(3, 4, 2, 1),
    lawful: true,
  },
  {
    id: 'trade_hub',
    produces: { textiles: 0.5, spirits: 0.5, art: 0.5, gems: 0.4, protein: 0.3 },
    consumes: {
      computers: 0.5,
      robotics: 0.5,
      optics: 0.4,
      gems: 0.5,
      art: 0.5,
      medicine: 0.4,
      vaccines: 0.5,
      spirits: 0.5,
    },
    shipyard: 3,
    cartography: true,
    intel: true,
    blackMarket: false,
    contractBias: { freight: 3, courier: 3, passenger: 3, supply: 1 },
    weight: w(6, 4, 1, 0.3),
    lawful: true,
  },
  {
    id: 'research',
    produces: { biosamples: 0.8, crystals: 0.4, optics: 0.4, rare_metals: 0.3 },
    consumes: {
      electronics: 0.7,
      computers: 0.7,
      fusion_cells: 0.7,
      protein: 0.6,
      fresh_produce: 0.6,
      spare_parts: 0.6,
    },
    shipyard: 1,
    cartography: true,
    intel: false,
    blackMarket: false,
    contractBias: { survey: 4, rescue: 3, courier: 2 },
    weight: w(0.5, 2, 4, 5),
    lawful: true,
  },
  {
    id: 'pirate',
    produces: { narcotics: 0.9, contraband_arms: 0.7, stolen_data: 0.7, gems: 0.4, rare_metals: 0.3 },
    consumes: {
      protein: 0.6,
      grain: 0.5,
      spirits: 0.7,
      medicine: 0.6,
      fusion_cells: 0.6,
      machinery: 0.5,
      art: 0.5,
      textiles: 0.4,
    },
    shipyard: 1,
    cartography: false,
    intel: false,
    blackMarket: true,
    contractBias: { courier: 3, freight: 2, passenger: 1 },
    weight: w(1.5, 1, 2.5, 3),
    lawful: false,
  },
];

export const STATION_TYPES_BY_ID = Object.fromEntries(STATION_TYPES.map((s) => [s.id, s])) as Record<
  StationTypeId,
  StationTypeDef
>;
